// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWWrP38wHsPNEAx3K_67RcaT3juIRQGU',
    appId: '1:778026764896:web:49ae56dda1433981e5d105',
    messagingSenderId: '778026764896',
    projectId: 'fitforge-ai-24993',
    authDomain: 'fitforge-ai-24993.firebaseapp.com',
    storageBucket: 'fitforge-ai-24993.firebasestorage.app',
    measurementId: 'G-8YEQLSW826',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxFWfK30vPp9QZ4aNPRXbkdIhi_4kdrY',
    appId: '1:778026764896:android:fbe238e8f7a1a033e5d105',
    messagingSenderId: '778026764896',
    projectId: 'fitforge-ai-24993',
    storageBucket: 'fitforge-ai-24993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oUdgixGECTrvITmZf-qKrmgET21PnQ8',
    appId: '1:778026764896:ios:8dc06ad5cc509a33e5d105',
    messagingSenderId: '778026764896',
    projectId: 'fitforge-ai-24993',
    storageBucket: 'fitforge-ai-24993.firebasestorage.app',
    iosClientId: '778026764896-75vggbolr9cfg3nssg75uc98jlkorvj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oUdgixGECTrvITmZf-qKrmgET21PnQ8',
    appId: '1:778026764896:ios:8dc06ad5cc509a33e5d105',
    messagingSenderId: '778026764896',
    projectId: 'fitforge-ai-24993',
    storageBucket: 'fitforge-ai-24993.firebasestorage.app',
    iosClientId: '778026764896-75vggbolr9cfg3nssg75uc98jlkorvj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArWWrP38wHsPNEAx3K_67RcaT3juIRQGU',
    appId: '1:778026764896:web:8a81a98b16fc83bae5d105',
    messagingSenderId: '778026764896',
    projectId: 'fitforge-ai-24993',
    authDomain: 'fitforge-ai-24993.firebaseapp.com',
    storageBucket: 'fitforge-ai-24993.firebasestorage.app',
    measurementId: 'G-2EJBRSZ82M',
  );
}
